spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: "${PASSWORD}"
    url: jdbc:mysql://localhost:3306/car_rental_system?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: "${USERNAME}"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
